"""ulog.testing — pytest plugin and programmatic test-event APIs.

Sub-package home for v0.3 test integration and v0.5 replay tooling:

- ``pytest_plugin`` module — auto-discovered via
  ``[project.entry-points.pytest11]``. Loaded by pytest itself, not
  imported manually.
- ``test_event`` (Story 1.9) — programmatic ``@contextmanager`` for
  non-pytest runners.
- ``replay_records`` (Story 4.9 / v0.5) — STUB in v0.3; importable name
  only. Architecture.md Gap G5 anchor.
- ``TestSession`` (v0.5) — STUB dataclass; importable name only.

The sub-package is loaded only when the ``[testing]`` extra is installed.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

from .test_event import test_event

__all__ = ["TestSession", "replay_records", "test_event"]


def replay_records(
    records: Sequence[Mapping[str, Any]],
) -> Any:
    """STUB — full implementation in v0.5 (Story 4.9).

    The IMPORTABLE NAME is locked here per architecture.md Gap G5: code
    that will be generated by ``replay_to_pytest()`` (v0.5) imports
    ``replay_records`` from this module. v0.3 publishes the name only;
    calling it raises NotImplementedError. The return type is `Any` for
    v0.3 — Story 4.9 will pin the final shape (likely a context manager
    yielding a `ReplaySession`).
    """
    raise NotImplementedError(
        "replay_records is implemented in v0.5 (Story 4.9). "
        "v0.3 publishes the importable name to lock the API surface "
        "per architecture.md Gap G5."
    )


@dataclass
class TestSession:
    """STUB dataclass — full implementation in v0.5.

    The shape is locked here per architecture.md (step-06 sub-package
    layout names this class as exported from ``ulog.testing``) to allow
    v0.3 client code to ``from ulog.testing import TestSession`` without
    ImportError. The ``name`` + ``records`` fields are minimal
    placeholders; v0.5 (Story 4.9) will pin the final shape in its own
    architectural review.
    """

    name: str = ""
    records: list[Any] = field(default_factory=list)

    # No __post_init__ defined — a `pass`-only post-init would add a
    # call-frame on every construction with zero behavior. Construction is
    # allowed by the dataclass-generated __init__; v0.5 (Story 4.9) will
    # decide whether to add validation or full session semantics.
